{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import time\n",
    "import numpy as np\n",
    "import dask.array as da\n",
    "import metpy.constants as mpconsts\n",
    "import metpy.units as units\n",
    "from func import cal_buoyancy  # import the function from your script\n",
    "from pathlib import Path\n",
    "import pandas as pd\n",
    "from dask import delayed\n",
    "from dask.distributed import Client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "backup_dir = Path.home() / \"backup_data\"\n",
    "\n",
    "backup_dir.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# path to interpolated humidity, pressure, and temperature \n",
    "file_path_main_arrays = backup_dir / \"backup_arrays_for_buoyancy.npz\"\n",
    "# path to times, latitudes and longitudes\n",
    "file_path_metadata = backup_dir / \"backup_metadata_for_buoyancy.npz\"\n",
    "\n",
    "# Load the saved arrays\n",
    "data = np.load(file_path_main_arrays, mmap_mode='r')\n",
    "print(\"file containing arrays loaded\")\n",
    "\n",
    "interpolated_pressure = da.from_array(data[\"array1\"], chunks=\"auto\")\n",
    "interpolated_q = da.from_array(data[\"array2\"], chunks=\"auto\")\n",
    "interpolated_t = da.from_array(data[\"array3\"], chunks=\"auto\")\n",
    "interpolated_qfit = da.from_array(data[\"array_4\"], chunks=\"auto\")\n",
    "print(\"Arrays loaded successfully!\")\n",
    "\n",
    "metadata = np.load(file_path_metadata)\n",
    "times = metadata['times']\n",
    "lats = metadata['lats']\n",
    "lons = metadata['lons']\n",
    "interpolated_altitudes = np.arange(0, 4000 + 20, 20)  # Assuming altitudes are fixed\n",
    "print(\"Metadata loaded successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-02-07 09:38:37,919 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n",
      "2025-02-07 09:38:37,933 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n",
      "2025-02-07 09:38:37,944 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n",
      "2025-02-07 09:38:37,953 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n",
      "2025-02-07 09:38:37,963 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-02-07 09:38:37,971 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n",
      "2025-02-07 09:38:37,980 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n",
      "2025-02-07 09:38:37,989 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n",
      "2025-02-07 09:38:37,997 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n",
      "2025-02-07 09:38:38,005 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 448, in instantiate\n",
      "    result = await self.process.start()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/nanny.py\", line 712, in start\n",
      "    self.init_result_q = mp_ctx.Queue()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/synchronize.py\", line 80, in __init__\n",
      "    register(self._semlock.name, \"semaphore\")\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 147, in register\n",
      "    self._send('REGISTER', name, rtype)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 154, in _send\n",
      "    self.ensure_running()\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/resource_tracker.py\", line 121, in ensure_running\n",
      "    pid = util.spawnv_passfds(exe, args, fds_to_pass)\n",
      "  File \"/home/annierosen16/anaconda3/envs/annieenv/lib/python3.9/multiprocessing/util.py\", line 452, in spawnv_passfds\n",
      "    return _posixsubprocess.fork_exec(\n",
      "OSError: [Errno 12] Cannot allocate memory\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[10], line 13\u001b[0m\n\u001b[1;32m      9\u001b[0m g \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m9.80665\u001b[39m  \u001b[38;5;66;03m# Gravity (m/s^2)\u001b[39;00m\n\u001b[1;32m     11\u001b[0m \u001b[38;5;66;03m# Dask Client for parallel processing\u001b[39;00m\n\u001b[0;32m---> 13\u001b[0m client \u001b[38;5;241m=\u001b[39m \u001b[43mClient\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     15\u001b[0m \u001b[38;5;129m@delayed\u001b[39m\n\u001b[1;32m     16\u001b[0m \n\u001b[1;32m     17\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mcompute_buoyancy_at_point\u001b[39m(latidx, lonidx, tidx, interpolated_pressure, \n\u001b[1;32m     18\u001b[0m                               interpolated_t, interpolated_qfit, interpolated_q, alt):\n\u001b[1;32m     20\u001b[0m     start_time \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()\n",
      "File \u001b[0;32m~/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/client.py:1014\u001b[0m, in \u001b[0;36mClient.__init__\u001b[0;34m(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, connection_limit, **kwargs)\u001b[0m\n\u001b[1;32m   1011\u001b[0m preload_argv \u001b[38;5;241m=\u001b[39m dask\u001b[38;5;241m.\u001b[39mconfig\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mdistributed.client.preload-argv\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m   1012\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpreloads \u001b[38;5;241m=\u001b[39m preloading\u001b[38;5;241m.\u001b[39mprocess_preloads(\u001b[38;5;28mself\u001b[39m, preload, preload_argv)\n\u001b[0;32m-> 1014\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstart\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1015\u001b[0m Client\u001b[38;5;241m.\u001b[39m_instances\u001b[38;5;241m.\u001b[39madd(\u001b[38;5;28mself\u001b[39m)\n\u001b[1;32m   1017\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdistributed\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mrecreate_tasks\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ReplayTaskClient\n",
      "File \u001b[0;32m~/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/client.py:1216\u001b[0m, in \u001b[0;36mClient.start\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m   1214\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_started \u001b[38;5;241m=\u001b[39m asyncio\u001b[38;5;241m.\u001b[39mensure_future(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_start(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs))\n\u001b[1;32m   1215\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m-> 1216\u001b[0m     \u001b[43msync\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mloop\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_start\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/utils.py:431\u001b[0m, in \u001b[0;36msync\u001b[0;34m(loop, func, callback_timeout, *args, **kwargs)\u001b[0m\n\u001b[1;32m    429\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    430\u001b[0m     \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m e\u001b[38;5;241m.\u001b[39mis_set():\n\u001b[0;32m--> 431\u001b[0m         \u001b[43mwait\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m10\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m    433\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m error \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    434\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m error\n",
      "File \u001b[0;32m~/anaconda3/envs/annieenv/lib/python3.9/site-packages/distributed/utils.py:420\u001b[0m, in \u001b[0;36msync.<locals>.wait\u001b[0;34m(timeout)\u001b[0m\n\u001b[1;32m    418\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mwait\u001b[39m(timeout: \u001b[38;5;28mfloat\u001b[39m \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mbool\u001b[39m:\n\u001b[1;32m    419\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 420\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43me\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    421\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyboardInterrupt\u001b[39;00m:\n\u001b[1;32m    422\u001b[0m         loop\u001b[38;5;241m.\u001b[39madd_callback(cancel)\n",
      "File \u001b[0;32m~/anaconda3/envs/annieenv/lib/python3.9/threading.py:581\u001b[0m, in \u001b[0;36mEvent.wait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    579\u001b[0m signaled \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_flag\n\u001b[1;32m    580\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m signaled:\n\u001b[0;32m--> 581\u001b[0m     signaled \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_cond\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    582\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m signaled\n",
      "File \u001b[0;32m~/anaconda3/envs/annieenv/lib/python3.9/threading.py:316\u001b[0m, in \u001b[0;36mCondition.wait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    314\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    315\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m timeout \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[0;32m--> 316\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m \u001b[43mwaiter\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43macquire\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    317\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    318\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m waiter\u001b[38;5;241m.\u001b[39macquire(\u001b[38;5;28;01mFalse\u001b[39;00m)\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "# Define array shapes\n",
    "\n",
    "all_blt = np.full((times.shape[0], lats.size, lons.size), np.nan)\n",
    "\n",
    "all_blc = np.full((times.shape[0], lats.size, lons.size), np.nan)\n",
    "\n",
    "alt = interpolated_altitudes\n",
    "\n",
    "g = 9.80665  # Gravity (m/s^2)\n",
    "\n",
    "# Dask Client for parallel processing\n",
    "\n",
    "client = Client()\n",
    "\n",
    "@delayed\n",
    "\n",
    "def compute_buoyancy_at_point(latidx, lonidx, tidx, interpolated_pressure, \n",
    "                              interpolated_t, interpolated_qfit, interpolated_q, alt):\n",
    "    \n",
    "    start_time = time.time()\n",
    "    \n",
    "    p = interpolated_pressure[tidx, :, latidx, lonidx].compute()\n",
    "    \n",
    "    t = interpolated_t[tidx, :, latidx, lonidx].compute()\n",
    "    \n",
    "    qlc = interpolated_qfit[tidx, :, latidx, lonidx].compute()\n",
    "    \n",
    "    qr = interpolated_q[tidx, :, latidx, lonidx].compute()\n",
    "\n",
    "    # Calculate buoyancy for ql and qr profiles\n",
    "    \n",
    "    b_qr = cal_buoyancy(t_profile=t, h_profile=qr, p_profile=p, alt_profile=alt)\n",
    "    \n",
    "    b_qlc = cal_buoyancy(t_profile=t, h_profile=qlc, p_profile=p, alt_profile=alt)\n",
    "\n",
    "    # Convert to Kelvin and calculate the buoyancy difference\n",
    "    \n",
    "    pprof_qr = (b_qr.tp) * units.degK\n",
    "    \n",
    "    pprof_qlc = (b_qlc.tp) * units.degK\n",
    "    \n",
    "    t = t * units.degC\n",
    "    \n",
    "    t = t.to(units.degK)\n",
    "\n",
    "    y_qr = pprof_qr - t\n",
    "    \n",
    "    y_qlc = pprof_qlc - t\n",
    "\n",
    "    pres_100 = p[0] - 100\n",
    "    \n",
    "    pres_300 = p[0] - 300\n",
    "    \n",
    "    pres_mask = (p >= pres_300) & (p <= pres_100)\n",
    "\n",
    "    altmask = (alt >= 2000) & (alt <= 4000)\n",
    "\n",
    "    x_clipped = p[altmask]\n",
    "    \n",
    "    y_clipped_qr = y_qr[altmask]\n",
    "    \n",
    "    y_clipped_qlc = y_qlc[altmask]\n",
    "\n",
    "    br = (mpconsts.Rd * np.trapz(y_clipped_qr[::-1], np.log(x_clipped[::-1]))).to(units('J/kg'))\n",
    "    \n",
    "    blc = (mpconsts.Rd * np.trapz(y_clipped_qlc[::-1], np.log(x_clipped[::-1]))).to(units('J/kg'))\n",
    "\n",
    "    blt = br - blc\n",
    "    \n",
    "    end_time = time.time()\n",
    "    \n",
    "    duration = end_time - start_time\n",
    "    \n",
    "    print(f\"Time for latidx={latidx}, lonidx={lonidx}, tidx={tidx}: {duration:.4f} seconds\")\n",
    "\n",
    "\n",
    "    return tidx, latidx, lonidx, blt.magnitude, blc.magnitude\n",
    "\n",
    "# Create a list of delayed tasks for each (latidx, lonidx, tidx)\n",
    "tasks = []\n",
    "\n",
    "for latidx in range(lats.size):\n",
    "    \n",
    "    for lonidx in range(lons.size):\n",
    "        \n",
    "        for tidx in range(times.shape[0]):\n",
    "            \n",
    "            task = compute_buoyancy_at_point(latidx, lonidx, tidx, \n",
    "                                             interpolated_pressure, interpolated_t, \n",
    "                                             interpolated_qfit, interpolated_q, alt)\n",
    "            \n",
    "            tasks.append(task)\n",
    "\n",
    "# Compute all tasks in parallel\n",
    "results = client.compute(tasks, sync=True)\n",
    "\n",
    "# Store the results in the all_blt and all_blc arrays\n",
    "for result in results:\n",
    "    \n",
    "    tidx, latidx, lonidx, blt_value, blc_value = result\n",
    "    \n",
    "    all_blt[tidx, latidx, lonidx] = blt_value\n",
    "    \n",
    "    all_blc[tidx, latidx, lonidx] = blc_value\n",
    "\n",
    "# # **Save the results**\n",
    "# output_dir = Path.home() / \"buoyancy_arrays\"\n",
    "# output_dir.mkdir(parents=True, exist_ok=True)\n",
    "# output_path = output_dir / \"computed_buoyancy.npz\"\n",
    "# np.savez(output_path, all_blt=all_blt, all_blc=all_blc)\n",
    "# print(f\"\\nBuoyancy arrays saved at: {output_path}\")\n",
    "\n",
    "# Close the Dask client\n",
    "client.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "annieenv",
   "language": "python",
   "name": "annieenv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
